/*
 * File:checkerBall.java
 * ----------------------
 * It is a graphics program where it draws ckecked ball with 
 * different colors generated by random generator
 */
import acm.program.*;
import acm.graphics.*;
import acm.util.*;

//It extends graphicsProgram
public class CheckerBall extends GraphicsProgram{
	
	//Number of rows
	private static final int NROWS = 10;
	//Number of columns
	private static final int NCOLUMNS = 16;
	
	public void run(){
		
		//get the size of the circle to be drawn
		int circleSize = getHeight()/NROWS;
		
		//draws the checker balls
		for(int i=0; i<NROWS; i++){
			for(int j=0; j<NCOLUMNS; j++){
				int x = j*circleSize;
				int y = i*circleSize;
				GOval ball = new GOval(x,y,circleSize,circleSize);
				ball.setFilled(true);
				ball.setColor(rgen.nextColor());
				add(ball);
			}
		}
	}
	
	//Generators random colors.
	private RandomGenerator rgen = RandomGenerator.getInstance();
}